// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7tJVxHkcVhWwCxI0Rp_WA4VVvt8JJoU',
    appId: '1:493000125330:web:dec1c289bbdd4e75686f4b',
    messagingSenderId: '493000125330',
    projectId: 'institute-saas',
    authDomain: 'institute-saas.firebaseapp.com',
    storageBucket: 'institute-saas.firebasestorage.app',
    measurementId: 'G-0LDCXVTV7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyab9NRuuZCFn_NI4zoibjl2nJBBhB9iY',
    appId: '1:493000125330:android:8b9eef8bbbd7fb24686f4b',
    messagingSenderId: '493000125330',
    projectId: 'institute-saas',
    storageBucket: 'institute-saas.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe7tJVxHkcVhWwCxI0Rp_WA4VVvt8JJoU',
    appId: '1:493000125330:web:0da440f84ca33a3a686f4b',
    messagingSenderId: '493000125330',
    projectId: 'institute-saas',
    authDomain: 'institute-saas.firebaseapp.com',
    storageBucket: 'institute-saas.firebasestorage.app',
    measurementId: 'G-TTX7FT7Y14',
  );
}
